### ISSUE TITLE
new variables for tab-->header-->button.scss

### ISSUE THREAD

**Issue by MRHajari** [neomjs/neo#4059]
These variables are missing in the theme tab-->header-->button.scss. please add those.
 'tab-button-background-color'     
 'tab-button-background-color-active'    
 'tab-button-background-color-disabled'  
 'tab-button-background-color-hover'   
 'tab-button-gap'         
 'tab-button-height-active'           
 'tab-button-height-disabled'    
  'tab-button-width'     
 'tab-button-padding-active'          
 'tab-button-padding-disabled'

**Comment by tobiu** [comment]
i am not sure about `tab-button-width` => a tab should adjust to the width of its content. e.g. inside our forms we have use cases where a tab header only contains a number like `1`, `2`, `3`. if there was a fixed (minimum?) width on theme level, they might get too wide.

we can still change widths on JS level.

thoughts? @mxmrtns

**Comment by tobiu** [comment]
actually one more question: can a tab header button `padding` change for different states? i imagine that this could break the layout.

**Comment by MRHajari** [comment]
You're right. can we have tab-button-minWidth?

**Comment by tobiu** [comment]
to give you guys an update:
<img width="573" alt="Screenshot 2023-02-16 at 22 44 46" src="https://user-images.githubusercontent.com/1177434/219598857-8168acc2-376a-4b2d-b185-eef6ca1677e5.png">

<img width="558" alt="Screenshot 2023-02-16 at 23 27 07" src="https://user-images.githubusercontent.com/1177434/219598881-a4dcc1bd-af04-46d3-be27-261fe8473f04.png">

<img width="554" alt="Screenshot 2023-02-16 at 23 16 41" src="https://user-images.githubusercontent.com/1177434/219598891-52547b20-de04-4cd6-88bf-4227505cd3e4.png">

<img width="563" alt="Screenshot 2023-02-16 at 23 19 43" src="https://user-images.githubusercontent.com/1177434/219598916-7cb722fa-89fe-47a3-aed1-2675479923fc.png">

some of the variables took quite some effort, since we do have 4 different header positions in place.

drag&drop ops do not honor the potential gap yet, i will create a follow up ticket for this one.

in general: tabs should use one of the button uis (secondary or ghost i guess), so we can define this one inside the `Overwrites.mjs` inside an app.

since tab header buttons are extending button and use their CSS rules, a tab button itself should only contain additional logic on top. so i am not 100% sure if we should keep e.g. background-colors for different states.
