### ISSUE TITLE
form.field.Phone : Phone number validation is required

### ISSUE THREAD

**Issue by PriyankaTakalkar** [neomjs/neo#4368]
Current result: no error message when filling in fields that logically should only be filled with numbers.

Expected result: Error message should appear when exiting the fields.

**Comment by tobiu** [comment]
Hi @PriyankaTakalkar!

The question is based on which logic? :)

https://html.spec.whatwg.org/multipage/input.html#telephone-state-(type=tel)
says that there is no generic recommendation, since phone numbers vary too much for given countries.

We can provide a basic input pattern like only allowing numbers and + (at the start) and maybe () and -. However, for your project, we do need more input if we want to enforce something more strict like the form field placeholder syntax.

Adding Max here as well: @mxmrtns.

**Comment by tobiu** [comment]
super simplified:
`inputPattern: /^[0-9\-+\(\) ]+$/,`

feel free to add smarter solutions
