### ISSUE TITLE
table.View: onStoreRecordChange only cellnode.innerHTML got update but the renderer don't get call again

### ISSUE THREAD

**Issue by pensuwan-k** [neomjs/neo#4584]

**Comment by tobiu** [comment]
this one will take a bit longer.

`createViewData()` does several transformations with a given rendererOutput, depending on the type. we need to extract this code into a new method, which we can then use inside `onStoreRecordChange()` as well.

**Comment by tobiu** [comment]
the renderer logic got moved into `applyRendererOutput()`.

there is a catch though: `onStoreRecordChange()` had a specific node and was relying on getting an innerHTML string. this enabled us to trigger a delta update manually.

now a cell can contain more complex json based vdom, so that we do need to ping the vdom worker for a real update cycle. for a table view, this can be a complex operation.

strong recommendation: if you need to change multiple record fields at once, please use a bulk update via `set()` and don't change fields one by one.

i will create a new ticket for allowing partial vdom updates.
