### ISSUE TITLE
Tutorials Todo List

### ISSUE THREAD

**Issue by tobiu** [neomjs/neo#5708]
@gplanansky @maxrahder: i started this one quite a while ago, but have not found the time to finish it.

It should probably get moved into "Guides", since it is not containing Labs for active coding.

We need to decide if we need it for v1.

**Comment by gplanansky** [comment]
Not necessary for v1, so do not hold up v1 for it.

The charm of todo list examples, is that they illustrate important framework features. 
MDM does todo list as a framework documentation _standard example_ for vue, react.

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks#vue_tutorials

And Vue uses todo list as example of MVVM:
https://012.vuejs.org/guide/

We want such an example, because interested developers use it to learn and compare Neo's way, vs react, vue or another framework.

_Not necessarily v1._   Not in the tutorial, so we don't need to hold up v1.    

The tutorial is a cadenced, building-on progression of choreographed examples.   Whereas the MDN/Vue.org examples  are a standalone discussions that use this standard example to speak to a particular well-known web coding pattern (MVVM) and a framework feature (data reactivity), with code that implements it.   

So we can add todo list any time.
